name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set environment variable for BASE_URL
        run: echo "REACT_APP_BASE_URL=http://51.136.116.54:11434" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build --build-arg REACT_APP_BASE_URL=http://51.136.116.54:11434 -t "${{ secrets.DOCKER_USERNAME }}"/tesla-chatbot-frontend:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/tesla-chatbot-frontend:latest
